export XDG_CONFIG_HOME=${HOME}/.config
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_DATA_HOME=${HOME}/.local/share

typeset -U PATH path
export PATH="${HOME}/bin:$HOME/.local/bin:${PATH}:$HOME/.local/share/npm/bin"

export PNPM_HOME="/home/geo/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

export HISTFILE="$XDG_DATA_HOME/zsh/history"
if [ ! -d $(dirname $HISTFILE) ]; then mkdir -p $(dirname $HISTFILE); fi

export HISTSIZE=10000
export SAVEHIST=10000

# export ZCOMPDUMP=$XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION
export ZCOMPCACHE="$XDG_CACHE_HOME/zsh/zcompcache"
export ZCOMPDUMP="$XDG_CACHE_HOME/zsh/zcompdump"
if [ ! -d $(dirname $ZCOMPDUMP) ]; then mkdir -p $(dirname $ZCOMPDUMP); fi

export EDITOR=code
export TERM=kitty
export PAGER=less

if command -v bat >/dev/null 2>&1; then
    export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

export _Z_DATA="$XDG_DATA_HOME"/z/data
if [ ! -d $(dirname $_Z_DATA) ]; then mkdir -p $(dirname $_Z_DATA); fi

export ZPLUG_LOADFILE="$XDG_CONFIG_HOME/zsh/plugins.zsh"

export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc

# makepkg (https://wiki.archlinux.org/title/Makepkg#Improving_compile_times)
export MAKEFLAGS="-j$(nproc)"

# community/vivid
export LS_COLORS="$(vivid generate snazzy)"

# Opt out of dotnet telemetry
export DOTNET_CLI_TELEMETRY_OPTOUT=1
