
[theme]
theme = "nord-dark"

[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
format = " $title.str(max_w:100) | "

[[block]]
block = "pacman"
interval = 600
format = " $icon $both updates ($aur aur ) "
format_singular = " $icon $both update "
format_up_to_date = " $icon up to date "
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "paru -Qua"
[[block.click]]
button = "left"
cmd = "~/.config/rofi/bin/updates.sh"

# [[block]]
# block = "temperature"
# format = "{average}"
# interval = 10
# # chip = "*-isa-*"

# [[block]]
# block = "nvidia_gpu"
# interval = 1
# info = 80
# warning = 90
# show_temperature = true
# show_utilization = false
# show_memory = false
# show_fan_speed = true
# label = ""

[[block]]
block = "github"
format = " $icon $total "
if_command = "env | grep I3RS_GITHUB_TOKEN"
[[block.click]]
button = "left"
cmd = "firefox https://github.com/notifications"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
# driver = "localebus"
# interval = 1

[[block]]
block = "time"
interval = 5
format = "$icon $timestamp.datetime(f:'%a %d/%m %R')"
[[block.click]]
button = "left"
cmd = "gsimplecal"

[[block]]
block = "sound"
# driver = "pulseaudio"
# format = "{output_name} {volume}"
# format = "$icon $volume"
headphones_indicator = true
# [block.mappings]
# "alsa_output.pci-0000_00_1f.3.analog-stereo" = ""
# "alsa_output.pci-0000_01_00.1.hdmi-stereo" = ""
# "bluez_output.04_52_C7_7E_46_4C.a2dp-sink" = ""
# "bluez_output.20_21_08_11_39_3B.headset-head-unit" = ""

[[block]]
block = "notify"