theme = "nord-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} +{aur} = {both} updates available"
format_singular = "{both} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "paru -Qua"
on_click = "fakeroot pacman -Qu --dbpath /tmp/checkup-db-geo/ | rofi -dmenu"

[[block]]
block = "github"
format = "{total}"
on_click = "firefox https://github.com/notifications"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 15

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "notify"