# theme = "nord-dark"
# icons = "awesome6"
# icons = "material-nf"
# icons_format = " <span stretch='ultraexpanded'>{icon}</span> "

[theme]
name = "nord-dark"
# [theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#abcdef"

[icons]
name = "awesome6"
[icons.overrides]
gpu = ""

[[block]]
block = "focused_window"
max_width = 100
show_marks = "visible"

[[block]]
block = "pacman"
interval = 600
format = "{both} updates ({aur} aur )"
format_singular = "{both} update"
format_up_to_date = "up to date"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "paru -Qua"
on_click = "fakeroot paru -Qu --dbpath /tmp/checkup-db-geo/ | rofi -dmenu"

# [[block]]
# block = "temperature"
# format = "{average}"
# interval = 10
# # chip = "*-isa-*"

# [[block]]
# block = "nvidia_gpu"
# interval = 1
# info = 80
# warning = 90
# show_temperature = true
# show_utilization = false
# show_memory = false
# show_fan_speed = true
# label = ""

[[block]]
block = "github"
format = "{total}"
on_click = "firefox https://github.com/notifications"
if_command = "env | grep I3RS_GITHUB_TOKEN"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
# driver = "localebus"
# interval = 1

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
on_click = "gsimplecal"

[[block]]
block = "sound"
# driver = "pulseaudio"
format = "{output_name} {volume}"
[block.mappings]
"alsa_output.pci-0000_00_1f.3.analog-stereo" = ""
"alsa_output.pci-0000_01_00.1.hdmi-stereo" = ""
"bluez_output.04_52_C7_7E_46_4C.a2dp-sink" = ""
"bluez_output.20_21_08_11_39_3B.headset-head-unit" = ""

[[block]]
block = "notify"